jobs:
  - job: LinuxBuild
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: "V Linux Build"
    steps:
      - script: |
        sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libcurl3-dev
        displayName: 'Install Dependencies'
      - script: |
        cd compiler && make
        displayName: 'Build V'
      - script: |
        make test
        displayName: 'Run Tests'
  - job: WindowsBuild
    pool: 
      vmImage: 'vs2017-win2016'
    displayName: "V Windows Build"
  - job: OSXBuild
    pool: 
      vmImage: 'macOS-10.13'
    displayName: "V MacOSX Build"
    steps:
      - script: |
        displayName: 'Install Dependencies'
      - script: |
          cd compiler && make && make test
        displayName: 'Build V'
