jobs:
  - job: LinuxBuild
    pool: 
      vmImage: 'ubuntu-16.04'
    displayName: "V Linux Build"
    steps:
      - script: |
          sudo apt install -y libglfw3 libglfw3-dev libfreetype6-dev libcurl3-dev
        displayName: 'Install Dependencies'
      - script: |
          make
        displayName: 'Build V'
      - script: |
          make test
        displayName: 'Run Tests'
  - job: WindowsBuild
    pool: 
      vmImage: 'vs2017-win2016'
    displayName: "V Windows Build"
  - job: OSXBuild
    pool: 
      vmImage: 'macOS-10.13'
    displayName: "V MacOSX Build"
    steps:
      - script: |
          brew install glfw freetype curl
        displayName: 'Install Dependencies'
      - script: |
          make && make test
        displayName: 'Build V'
trigger:
  branches:
    include:
      - '*'
pr:
  autoCancel: false
  branches:
    include:
      - '*'
